branch-defaults:
  default:
    environment: null
global:
  application_name: Tabbie
  default_ec2_keyname: JakobTabbie
  default_platform: PHP 5.6
  default_region: eu-central-1
  profile: eb-cli
  sc: null
